### ISSUE TITLE
Reusing/License?

### ISSUE THREAD

**Issue by llrs** [schochastics/cran-doomsday#2]
Hi! Many thanks for providing this web page.

I would like to provide the number of how fast all CRAN would be archived on a package I'm writing (this package is around answering question about repositories using their data). This would facilitate tracking this number along time to see the stability of CRAN (together with other data). 

Is it open to reuse? I don't see a license but I would like to use the GPL v3 license on that package.

**Comment by schochastics** [comment]
Hi @llrs, I had no license so far but for your convenience, I added the GPL v3 license now

**Comment by llrs** [comment]
Many thanks!! And cool idea and presentstion!
